version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    tty: true
    stdin_open: true

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    tty: true
    stdin_open: true
